version: "3.5"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: PiHole-01
    networks:
      pihole:
        ipv4_address: 10.20.30.1
        ipv6_address: 2000:3000:4000:1000:1::1
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - "TZ=Australia/Melbourne"
      - "PROXY_LOCATION=pihole"
      - "VIRTUAL_PORT=80"
      - "WEBPASSWORD=APasswordHere01"
      - "ServerIP=10.20.30.1"
      - "DNS1=10.20.30.2"
      - "DNS2=10.20.30.2"
    volumes:
      - "/etc/pihole/:/etc/pihole/"
      - "/etc/dnsmasq.d/:/etc/dnsmasq.d/"
      - "/var/log/pihole:/var/log/"
    restart: always

  dnscrypt-proxy:
    image: gists/dnscrypt-proxy
    container_name: dnscrypt-proxy
    hostname: DNSPROXY-01
    networks:
      pihole:
        ipv4_address: 10.20.30.2
        ipv6_address: 2000:3000:4000:1000:1::2
    ports:
        - "5053:53/udp"
        - "5053:53/tcp"
    volumes:
        - "./dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
        - "/var/log/dnscrypt-proxy:/var/log/"
    restart: always

networks:
  pihole:
    external:
      name: lan